name: CI PR on merged

on:
  pull_request:
    paths-ignore:
      - ".gitignore"
      - ".mockery.yaml"
      - "Containerfile"
      - "LICENSE"
      - "Makefile"
      - "README.md"
    types:
      - closed
    branches:
      - master

jobs:
  delivery:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/ci-delivery.yml
    secrets: inherit
    with:
      commit_sha: ${{ github.event.pull_request.merge_commit_sha }}